name: docker-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
    # 登录到 Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 构建并推送 Docker 镜像
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: sanbei/oj-back:latest